<?xml version="1.0" encoding="utf-8"?><Database Name="ManageCafeInternet" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ManageCafeInternet;User ID=sa" SettingsObjectName="CafeInternet.Properties.Settings" SettingsPropertyName="ManageCafeInternetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.area" Member="areas">
    <Type Name="area">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="area_computer" Member="computers" ThisKey="entity_id" OtherKey="area_id" Type="computer" />
    </Type>
  </Table>
  <Table Name="dbo.computer_status" Member="computer_status">
    <Type Name="computer_status">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="computer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="start_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="food_id" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="computer_status_order" Member="orders" ThisKey="entity_id" OtherKey="computer_status_id" Type="order" />
    </Type>
  </Table>
  <Table Name="dbo.food_type" Member="food_types">
    <Type Name="food_type">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="food_type_food" Member="foods" ThisKey="entity_id" OtherKey="food_type_id" Type="food" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="computer_status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="computer_status_order" Member="computer_status" ThisKey="computer_status_id" OtherKey="entity_id" Type="computer_status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.role" Member="roles">
    <Type Name="role">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="users" ThisKey="entity_id" OtherKey="role_id" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="role" ThisKey="role_id" OtherKey="entity_id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.computer" Member="computers">
    <Type Name="computer">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="area_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="total_used_time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="profit" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="area_computer" Member="area" ThisKey="area_id" OtherKey="entity_id" Type="area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.food" Member="foods">
    <Type Name="food">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="food_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="food_type_food" Member="food_type" ThisKey="food_type_id" OtherKey="entity_id" Type="food_type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.report" Member="reports">
    <Type Name="report">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="information" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="performer" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="activity" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.login_permission" Method="login_permission">
    <Parameter Name="account" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="login_permissionResult">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_infor" Method="get_infor">
    <Parameter Name="account" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="get_inforResult">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_food" Method="get_food">
    <ElementType Name="get_foodResult">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="food_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_price_area" Method="get_price_area">
    <ElementType Name="get_price_areaResult">
      <Column Name="Area" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Number of computers]" Member="Number_of_computers" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_area" Method="search_area">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="search_areaResult">
      <Column Name="Area" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Number of computers]" Member="Number_of_computers" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllComputersFromArea" Method="getAllComputersFromArea">
    <ElementType Name="getAllComputersFromAreaResult">
      <Column Name="[Computer Id]" Member="Computer_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Computer Name]" Member="Computer_Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>